hyprctl dispatch sendshortcut CTRL, K, class:discord
hyprctl dispatch sendshortcut , S, class:discord
hyprctl dispatch sendshortcut , i, class:discord
hyprctl dispatch sendshortcut , m, class:discord
hyprctl dispatch sendshortcut , o, class:discord
hyprctl dispatch sendshortcut , n, class:discord
hyprctl dispatch sendshortcut , d, class:discord
hyprctl dispatch sendshortcut , e, class:discord
hyprctl dispatch sendshortcut , n, class:discord
hyprctl dispatch sendshortcut , s, class:discord
hyprctl dispatch sendshortcut , n, class:discord
hyprctl dispatch sendshortcut , a, class:discord
hyprctl dispatch sendshortcut , k, class:discord
hyprctl dispatch sendshortcut , k, class:discord
hyprctl dispatch sendshortcut , e, class:discord
hyprctl dispatch sendshortcut , d, class:discord
hyprctl dispatch sendshortcut , e, class:discord
hyprctl dispatch sendshortcut , Return, class:discord
